- .travis.yml
- package.json
- src/services/notification.service.spec.ts
- src/wrappers/notifme.module.ts
> Test travis and added a test

- src/app.controller.ts
- src/templates/_layouts/email-transactional.html
> Added branding in email footer

- src/app.controller.ts
I need to test it before moving it from draft, but the code is strictly following the protocol and the comments and links should be enough for an initial review.
> Adjusted message acknowledgment strategy

- notifications.yml
- src/templates/user.application.applicant.js
- clean user application notification subject
- fixed a bug where global community admin credential was incorrect
> Misc fixes

- package-lock.json
- package.json
- src/services/domain/builders/communication-discussion-created/communication.discussion.created.notification.builder.ts
- src/services/domain/builders/communication-updated/communication.updated.notification.builder.ts
- src/templates/_layouts/email-transactional.html
- src/templates/user.application.applicant.js
-Requires auth policy reset if you want to toggle the new preferences on / off
> Notification preferences

- src/services/domain/builders/application-created/application.created.notification.builder.ts
- src/services/domain/builders/communication-discussion-created/communication.discussion.created.notification.builder.ts
- src/services/domain/builders/communication-updated/communication.updated.notification.builder.ts
- src/services/domain/builders/user-registered/user.registered.notification.builder.ts
> skipped a group check

- package-lock.json
- package.json
- src/common/constants/defaults.ts
- src/services/external/alkemio-client/alkemio.client.factory.ts
- src/utils/validate-connection.ts
> Update client-lib version

- README.md
- notifications.yml
- package-lock.json
- package.json
- src/services/application/template-to-credential-mapper/utils/utils.spec.ts
> Ecoverse -> Hub

- package-lock.json
- package.json
- src/templates/_layouts/email-transactional.html
I swear this took my too long to figure out - New Image added!
Update the link of the footer image
> Changed image url to new requested image

- notifications.yml
- package-lock.json
- package.json
- src/app.controller.ts
- src/app.module.ts
- src/common/constants/events.ts
- src/common/enums/email.template.ts
- src/core/contracts/notification.recipient.template.provider.interface.ts
- src/services/domain/builders/communication-discussion-created/communication.discussion.created.notification.builder.ts
- src/services/domain/builders/communication-updated/communication.updated.notification.builder.ts
- src/services/domain/builders/community-context-feedback/community.context.review.submitted.notification.builder.ts
- src/services/domain/builders/index.ts
- src/services/domain/notification/notification.service.spec.ts
- src/services/domain/notification/notification.service.ts
- src/templates/community.review.submitted.admin.js
- src/templates/community.review.submitted.reviewer.js
- src/types/communication.update.event.payload.d.ts
- src/types/community.context.review.submitted.payload.d.ts
> Added builder for community review notifications

- .github/workflows/build-deploy-k8s-dev-aws.yml
- .github/workflows/build-deploy-k8s-dev-azure.yml
- .github/workflows/build-deploy-k8s-test-azure.yml
- manifests/25-notifications-deployment-dev.yaml
Fixed workflow dispatch for CI
> AWS --> Azure

- src/templates/community.new.member.admin.js
Not tested but looks to be an obvious fix...
> fixed wrong field name in notification email template

- notifications.yml
- package-lock.json
- package.json
- src/services/domain/builders/aspect-created/aspect.created.notification.builder.ts
- src/services/domain/builders/communication-discussion-created/communication.discussion.created.notification.builder.ts
- src/services/domain/builders/communication-update-created/communication.update.created.notification.builder.ts
- Only the direct community to receive the user notifications
> Release: User notifications received only by the direct community

- notifications.yml
- package-lock.json
- package.json
- src/services/domain/builders/aspect-created/aspect.created.notification.builder.ts
- src/services/domain/builders/communication-discussion-created/communication.discussion.created.notification.builder.ts
- src/services/domain/builders/communication-update-created/communication.update.created.notification.builder.ts
- src/templates/_layouts/email-transactional.html
Notifications Patch 30-06-2022
Bug fix:
> Fix of notifications images footer endpoint

- notifications.yml
- package-lock.json
- package.json
- src/app.controller.ts
- src/app.module.ts
- src/common/constants/events.ts
- src/common/dto/community.collaboration.interest.payload.ts
- src/common/dto/index.ts
- src/common/enums/email.template.ts
- src/core/contracts/notification.recipient.template.provider.interface.ts
- src/services/domain/builders/communication-update-created/communication.update.created.notification.builder.ts
- src/services/domain/builders/community-collaboration-interest/community.collaboration.interest.notification.builder.ts
- src/services/domain/builders/index.ts
- src/services/domain/notification/notification.service.spec.ts
- src/services/domain/notification/notification.service.ts
- src/templates/community.collaboration.interest.admin.js
- src/templates/community.collaboration.interest.user.js
> Add community collaboration interest notifications.

- src/app.controller.ts
- src/common/email-template-payload/application.created.email.payload.ts
- src/common/email-template-payload/callout.published.email.payload.ts
- src/common/email-template-payload/communication.discussion.created.email.payload.ts
- src/common/email-template-payload/communication.update.created.email.payload.ts
- src/common/email-template-payload/community.collaboration.email.payload.ts
- src/common/email-template-payload/community.new.member.email.payload.ts
- src/services/domain/builders/application-created/application.created.notification.builder.ts
- src/services/domain/builders/callout-published/callout.published.notification.builder.ts
- src/services/domain/builders/communication-discussion-created/communication.discussion.created.notification.builder.ts
- src/services/domain/builders/communication-update-created/communication.update.created.notification.builder.ts
- src/services/domain/builders/community-collaboration-interest/community.collaboration.interest.notification.builder.ts
- src/services/domain/builders/community-new-member/community.new.member.notification.builder.ts
- src/templates/callout.published.member.js
> Fixed some fields on email templates

- package-lock.json
- package.json
- src/common/dto/application.created.event.payload.ts
- src/common/dto/communication.discussion.created.event.payload.ts
- src/common/dto/communication.update.event.payload.ts
- src/common/dto/community.collaboration.interest.payload.ts
- src/common/dto/community.new.member.payload.ts
- src/common/email-template-payload/application.created.email.payload.ts
- src/common/email-template-payload/community.collaboration.email.payload.ts
- src/common/enums/community.type.ts
- src/services/domain/builders/community-collaboration-interest/community.collaboration.interest.notification.builder.ts
- src/templates/community.collaboration.interest.admin.js
- src/templates/community.collaboration.interest.user.js
> updated payload for collaboration interest + associated email templates

- src/services/application/notification-builder/notification.builder.ts
> added extra logging

- notifications.yml
- package-lock.json
- package.json
Note: no client-web updates were needed
> added global hub admins to user registered; updated version

- src/common/email-template-payload/community.new.member.email.payload.ts
- src/services/domain/builders/community-new-member/community.new.member.notification.builder.ts
- src/templates/aspect.created.admin.js
- src/templates/aspect.created.member.js
- src/templates/community.new.member.admin.js
- User Registered Notification for Global Hub Admins
> Release: User Registered Notification for Global Hub Admins

- .gitignore
- Dockerfile
- package-lock.json
- service/.eslintrc.js
- service/package.json
> Fix paths in Dockerfile

- .github/workflows/build-deploy-k8s-dev-azure.yml
- .github/workflows/build-deploy-k8s-test-azure.yml
> Fix deployment yaml paths

- service/package.json
> Bump version

- .gitignore
- service/package-lock.json
- service/package.json
- service/src/services/domain/builders/platform-user-removed/platform.user.removed.notification.builder.ts
- Removed wrongly picked up user email in the User Removal flow
> Release: Fixed User Removal template payload

- service/package-lock.json
- service/package.json
- service/src/services/application/alkemio-url-generator/alkemio.url.generator.ts
- Fixed wrongly generated endpoint (`/explore` is now `/contribute`)
> Release: Fixed wrong callout endpoint (#172)

- service/package-lock.json
> Update package-lock file.

- service/package-lock.json
- service/package.json
- service/src/common/email-template-payload/communication.community.leads.message.email.payload.ts
- service/src/common/email-template-payload/communication.organization.mention.email.payload.ts
- service/src/common/email-template-payload/communication.organization.message.email.payload.ts
- service/src/common/email-template-payload/communication.user.mention.email.payload.ts
- service/src/common/email-template-payload/communication.user.message.email.payload.ts
- service/src/services/domain/builders/communication-community-message/communication.community.leads.message.notification.builder.ts
- service/src/services/domain/builders/communication-organization-mention/communication.organization.mention.notification.builder.ts
- service/src/services/domain/builders/communication-organization-message/communication.organization.message.notification.builder.ts
- service/src/services/domain/builders/communication-user-mention/communication.user.mention.notification.builder.ts
- service/src/services/domain/builders/communication-user-message/communication.user.message.notification.builder.ts
- service/src/templates/communication.comment.mention.organization.js
- service/src/templates/communication.comment.mention.user.js
- service/src/templates/communication.community.leads.message.recipient.js
- service/src/templates/communication.community.leads.message.sender.js
- service/src/templates/communication.organization.message.recipient.js
- service/src/templates/communication.organization.message.sender.js
- service/src/templates/communication.user.message.recipient.js
- service/src/templates/communication.user.message.sender.js
Added additional formatting.
Added links.
Suggested next actions where feasible.
> Refined contents of notification messages

- service/package-lock.json
- service/package.json
- service/src/services/domain/builders/communication-user-mention/communication.user.mention.notification.builder.ts
- service/src/utils/markdown-to-text.util.ts
- Notification templates now convert markdown to text
> Release:  Markdown to text

- service/package-lock.json
- service/package.json
- service/src/core/models/user.ts
- service/src/services/application/alkemio-client-adapter/alkemio.client.adapter.ts
- service/src/services/application/notification-builder/notification.builder.ts
- service/src/services/domain/builders/collaboration-context-feedback/collaboration.context.review.submitted.notification.builder.ts
- service/src/services/domain/builders/collaboration-interest/collaboration.interest.notification.builder.ts
- service/src/services/domain/builders/communication-community-message/communication.community.leads.message.notification.builder.ts
- service/src/services/domain/builders/communication-organization-mention/communication.organization.mention.notification.builder.ts
- service/src/services/domain/builders/communication-organization-message/communication.organization.message.notification.builder.ts
- service/src/services/domain/builders/communication-user-mention/communication.user.mention.notification.builder.ts
- service/src/services/domain/builders/communication-user-message/communication.user.message.notification.builder.ts
- service/src/services/domain/builders/community-application-created/community.application.created.notification.builder.ts
- service/src/services/domain/builders/community-new-member/community.new.member.notification.builder.ts
- service/src/services/domain/builders/platform-user-registered/platform.user.registered.notification.builder.ts
- service/test/data/admin.user.json
- service/test/data/challenge.admins.json
- service/test/data/opportunity.admins.json
> Service updates for profile entity changes.

- service/package-lock.json
- service/package.json
- service/src/core/models/user.ts
- service/src/services/application/alkemio-client-adapter/alkemio.client.adapter.ts
- service/src/services/application/notification-builder/notification.builder.ts
- service/src/services/domain/builders/collaboration-context-feedback/collaboration.context.review.submitted.notification.builder.ts
- service/src/services/domain/builders/collaboration-interest/collaboration.interest.notification.builder.ts
- service/src/services/domain/builders/communication-community-message/communication.community.leads.message.notification.builder.ts
- service/src/services/domain/builders/communication-organization-mention/communication.organization.mention.notification.builder.ts
- service/src/services/domain/builders/communication-organization-message/communication.organization.message.notification.builder.ts
- service/src/services/domain/builders/communication-user-mention/communication.user.mention.notification.builder.ts
- service/src/services/domain/builders/communication-user-message/communication.user.message.notification.builder.ts
- service/src/services/domain/builders/community-application-created/community.application.created.notification.builder.ts
- service/src/services/domain/builders/community-new-member/community.new.member.notification.builder.ts
- service/src/services/domain/builders/platform-user-registered/platform.user.registered.notification.builder.ts
- service/test/data/admin.user.json
- service/test/data/challenge.admins.json
- service/test/data/opportunity.admins.json
- Payloads updated to comply with the new `Profile` structure
> Release: Profile

- lib/package-lock.json
- lib/package.json
- lib/src/common/alkemio-url-generator/alkemio.url.generator.ts
- service/package-lock.json
- service/package.json
> Use new callout url format.

- lib/package-lock.json
- lib/package.json
- lib/src/common/alkemio-url-generator/alkemio.url.generator.ts
- service/package-lock.json
- service/package.json
- Updated URL format to use `/collaboration` instead of `/contribute/callouts`
> Release: Updated URL format for Callouts in Context

- lib/package-lock.json
- lib/package.json
- lib/src/common/alkemio-url-generator/alkemio.url.generator.ts
> Add forum discussion url builder.

- lib/package-lock.json
- lib/package.json
- lib/src/common/alkemio-url-generator/alkemio.url.generator.ts
- Added notification on forum discussion post
> Forum discussion notification

- service/package-lock.json
- service/package.json
> Minor version update

- lib/package-lock.json
- lib/package.json
- lib/src/dto/comment.reply.event.payload.ts
- lib/src/dto/index.ts
- lib/src/notification.event.type.ts
- service/notifications.yml
- service/package-lock.json
- service/package.json
- service/src/app.controller.ts
- service/src/app.module.ts
- service/src/common/email-template-payload/comment.reply.email.payload.ts
- service/src/common/email-template-payload/index.ts
- service/src/common/enums/email.template.ts
- service/src/core/contracts/notification.recipient.template.provider.interface.ts
- service/src/services/domain/builders/comment-reply/comment.reply.notification.builder.ts
- service/src/services/domain/builders/index.ts
- service/src/services/domain/notification/notification.service.spec.ts
- service/src/services/domain/notification/notification.service.ts
- service/src/templates/comment.reply.js
> Add comment reply notification.

- lib/package-lock.json
- lib/package.json
- lib/src/dto/comment.reply.event.payload.ts
- lib/src/dto/index.ts
- lib/src/notification.event.type.ts
- service/notifications.yml
- service/package-lock.json
- service/package.json
- service/src/app.controller.ts
- service/src/app.module.ts
- service/src/common/email-template-payload/comment.reply.email.payload.ts
- service/src/common/email-template-payload/index.ts
- service/src/common/enums/email.template.ts
- service/src/core/contracts/notification.recipient.template.provider.interface.ts
- service/src/services/domain/builders/comment-reply/comment.reply.notification.builder.ts
- service/src/services/domain/builders/index.ts
- service/src/services/domain/notification/notification.service.spec.ts
- service/src/services/domain/notification/notification.service.ts
- service/src/templates/comment.reply.js
- Added a `Notification` upon reply on a `Comment`
> Release: Comment Reply Notification

- service/src/templates/_layouts/email-transactional.html
- service/src/templates/community.invitation.created.invitee.js
> Fix broken url and space.

- service/src/templates/communication.user.message.recipient.js
> Fix spacing in direct message notification.

- service/src/templates/community.external.invitation.created.inviter.js
> Fix spacing.

- service/package-lock.json
- service/package.json
- service/src/templates/communication.user.message.recipient.js
- service/src/templates/community.external.invitation.created.inviter.js
- service/src/templates/community.user.application.admin.js
> Templates refresh feature

- service/notifications.yml
> Fix space community leads notification.

- service/src/services/domain/builders/collaboration-post-created/collaboration.post.created.notification.builder.ts
- service/src/services/domain/builders/collaboration-whiteboard-created/collaboration.whiteboard.created.notification.builder.ts
- service/src/services/domain/builders/community-application-created/community.application.created.notification.builder.ts
- service/src/services/domain/builders/community-new-member/community.new.member.notification.builder.ts
> Fix recipients for new post created notification.

- service/notifications.yml
- service/package-lock.json
- service/package.json
- service/src/services/domain/builders/collaboration-post-created/collaboration.post.created.notification.builder.ts
- service/src/services/domain/builders/collaboration-whiteboard-created/collaboration.whiteboard.created.notification.builder.ts
- service/src/services/domain/builders/community-application-created/community.application.created.notification.builder.ts
- service/src/services/domain/builders/community-new-member/community.new.member.notification.builder.ts
- Fixed the recipients for `New post created` notification
- Fixed the recipients for `Whiteboard created` notification
- Fixed the recipients for `Community application created` notification
- Fixed the recipients for `Community new member` notification
> Release: Fixes

- service/package-lock.json
- service/package.json
- service/src/templates/community.user.application.applicant.js
> Update user application email template.

- service/package-lock.json
- service/package.json
- service/src/templates/_layouts/email-transactional.html
- service/src/templates/comment.reply.js
- service/src/templates/communication.comment.mention.organization.js
- service/src/templates/communication.comment.mention.user.js
- service/src/templates/communication.community.leads.message.recipient.js
- service/src/templates/communication.community.leads.message.sender.js
- service/src/templates/communication.organization.message.recipient.js
- service/src/templates/communication.organization.message.sender.js
- service/src/templates/communication.user.message.recipient.js
- service/src/templates/communication.user.message.sender.js
- service/src/templates/community.external.invitation.created.invitee.js
- service/src/templates/community.external.invitation.created.inviter.js
- service/src/templates/community.invitation.created.invitee.js
> Preserve newlines in messages.

- .github/ISSUE_TEMPLATE/bug_report.md
> Update bug_report.md issue template with areas that will be affected

- .github/ISSUE_TEMPLATE/user_story.md
> Update user_story.md issue template with areas that will be affected

- service/package-lock.json
- service/package.json
- service/src/templates/_layouts/email-transactional.html
- service/src/templates/collaboration.callout.published.member.js
- service/src/templates/collaboration.discussion.comment.member.js
- service/src/templates/collaboration.interest.admin.js
- service/src/templates/collaboration.interest.user.js
- service/src/templates/collaboration.post.comment.owner.js
- service/src/templates/collaboration.post.created.admin.js
- service/src/templates/collaboration.post.created.member.js
- service/src/templates/collaboration.whiteboard.created.admin.js
- service/src/templates/collaboration.whiteboard.created.member.js
- service/src/templates/comment.reply.js
- service/src/templates/communication.comment.mention.organization.js
- service/src/templates/communication.comment.mention.user.js
- service/src/templates/communication.community.leads.message.recipient.js
- service/src/templates/communication.community.leads.message.sender.js
- service/src/templates/communication.update.admin.js
- service/src/templates/communication.update.member.js
- service/src/templates/community.external.invitation.created.inviter.js
- service/src/templates/community.invitation.created.invitee.js
- service/src/templates/community.new.member.admin.js
- service/src/templates/community.new.member.member.js
- service/src/templates/community.user.application.admin.js
- service/src/templates/community.user.application.applicant.js
- service/src/templates/platform.forum.discussion.comment.js
- service/src/templates/platform.forum.discussion.created.js
Change our current primary color (#065F6B) to #1D384A - [https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5402](https://github.com/alkem-io/client-web/pull/ticket)
> Change primary color

- service/src/services/domain/builders/community-application-created/community.application.created.notification.builder.ts
> Fix application created event template variable.

- service/src/templates/communication.user.message.recipient.js
> Remove misleading message in communication.user.message.recipient.js

- lib/package-lock.json
- lib/package.json
- lib/src/common/enums/role.change.type.ts
- lib/src/dto/index.ts
- lib/src/dto/platform.global.role.change.event.payload.ts
- lib/src/index.ts
- lib/src/notification.event.type.ts
- service/notifications.yml
- service/package-lock.json
- service/package.json
- service/src/app.controller.ts
- service/src/app.module.ts
- service/src/common/email-template-payload/platform.global.role.change.email.payload.ts
- service/src/common/enums/email.template.ts
- service/src/core/contracts/notification.recipient.template.provider.interface.ts
- service/src/services/domain/builders/platform-global-role-change/platform.global.role.change.notification.builder.ts
- service/src/services/domain/notification/notification.service.spec.ts
- service/src/services/domain/notification/notification.service.ts
- service/src/templates/platform.global.role.change.admin.js
new notifications-lib package
new notification type for changes in global roles
NOTE: uses user preference for users being registered, which is fine for now.
> added notification for changes in global roles

- Dockerfile
- service/notifications.yml
- service/package-lock.json
- service/package.json
- service/src/app.module.ts
- service/src/health.controller.ts
- service/src/main.ts
- Exposed port `4004` for a rest endpoint
- Exposed `/heatlh` endpoint for a simple health check. Will returns `200` if reachable.
> Health controller

- Dockerfile
- lib/package-lock.json
- lib/package.json
- lib/src/dto/index.ts
- lib/src/dto/virtual.contributor.invitation.created.event.payload.ts
- lib/src/notification.event.type.ts
- service/notifications.yml
- service/package-lock.json
- service/package.json
- service/src/app.controller.ts
- service/src/app.module.ts
- service/src/common/email-template-payload/index.ts
- service/src/common/email-template-payload/virtual.contributor.invitation.created.email.payload.ts
- service/src/common/enums/email.template.ts
- service/src/core/contracts/notification.recipient.template.provider.interface.ts
- service/src/health.controller.ts
- service/src/main.ts
- service/src/services/domain/builders/virtual-contributor-invitation-created/virtual.contributor.invitation.created.notification.builder.ts
- service/src/services/domain/notification/notification.service.spec.ts
- service/src/services/domain/notification/notification.service.ts
- service/src/templates/community.external.invitation.created.invitee.js
- service/src/templates/community.invitation.created.vc.host.js
- [Health controller](https://github.com/alkem-io/notifications/pull/324). 
- Exposed `/health` for health check
- [microservice reconnect options](https://github.com/alkem-io/notifications/pull/327/commits/b78d6c152939099dbfd1841423a7214b5fe51485)
- [Notification for Virtual Contributor invitation](https://github.com/alkem-io/notifications/pull/325)
> Release v0.17.3

- service/src/templates/community.new.member.admin.js
I added the word "The" at the beginning of the sentence, so it will always be capitalized 
The user ... has joined ...
The virtual contrinutor ... has joined ...
> Adding capitalization to new user/vc joined notification #342

- service/src/templates/_layouts/email-transactional.html
Changed to "Safe Spaces for Collaboration" as agreed
> Changing the notification e-mail footer to be consistent with website #341

- lib/package-lock.json
- lib/package.json
- lib/src/dto/contributor.payload.ts
- lib/src/dto/in-app/in.app.notification.community.new.member.payload.ts
- lib/src/dto/in-app/in.app.notification.contributor.mentioned.payload.ts
- lib/src/dto/platform.user.invited.to.role.event.payload.ts
- service/package-lock.json
- service/package.json
- service/src/services/builders/in-app/community.new.contributor.in.app.notification.builder.ts
- service/src/services/builders/in-app/contributor.mentioned.in.app.notification.builder.ts
- service/src/services/domain/builders/community-new-member/community.new.member.notification.builder.ts
* enums updated according to latest graphql schema
* lib version bump
* lib types updated
* service types updated
* bumped to using client-lib": "0.34.0"
* bump notifications-lib to version 0.10.2
- I understand that submitting the pull request …
> Schema update (#371)

- service/package-lock.json
- service/package.json
- service/src/templates/_layouts/email-transactional.html
> Update footer icons images and bump version (#395)

- service/src/app.controller.ts
- service/src/generated/alkemio-schema.ts
- service/src/services/notification/notification.service.ts
- service/test/data/event.application.created.payload.json
Depends on https://github.com/alkem-io/server/pull/5449
Note that the codegen was passing successfully. However, when compiling the service, there were errors. 
So this one (service) should be carefully monitored.
> Schema update and application sender cleanup
